apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - infrastructure-sync.yaml
  - apps/gps-service-sync.yaml
  - apps/pricing-service-sync.yaml
  - apps/request-service-sync.yaml
  - apps/driver-service-sync.yaml
