apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: rides.fct.riderequest.created
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000 # 7 days
    segment.bytes: 1073741824 # 1 GB
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: rides.fct.ride.accepted
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000 # 7 days
    segment.bytes: 1073741824 # 1 GB
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: rides.fct.payment.completed
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: rides.fct.payment.failed
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: rides.fct.driver.assigned
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: rides.fct.ride.completed
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: rides.fct.payment.completed
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: rides.fct.payment.failed
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
