apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: payment-service
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
    - name: mongodb
  interval: 10m
  path: ./k8s/apps/payment-service
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: ride-sharing
