name: Build All Microservices

on:
  push:
    branches: ["main"]
    paths: ["services/**"]
  pull_request:
    branches: ["main"]
    paths: ["services/**"]

permissions:
  contents: read
  packages: write

jobs:
  detect-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect services
        id: set-matrix
        run: |
          cd services
          # loop through directories and find dockerfiles
          SERVICES_JSON=$(for d in */; do if [ -f "$d/Dockerfile" ]; then echo "${d%/*}"; fi; done | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "matrix=$SERVICES_JSON" >> "$GITHUB_OUTPUT"

  build:
    needs: detect-services
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.detect-services.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}
          tags: |
            # :latest
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

            # :pr-x on pull requests
            type=ref,event=pr

            # :sha-xxx... on every commit
            type=sha,format=long

      - name: Build and push Docker Image for ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: services/${{ matrix.service }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
